# Generated by Django 5.2.11 on 2026-03-10 04:46

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_referraluser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pricing_signup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.pricingsignup')),
            ],
        ),
    ]
