# Generated by Django 5.2.11 on 2026-03-10 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhonePeTransaction',
        ),
    ]
