# Generated by Django 5.2.11 on 2026-03-10 06:35

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_delete_phonepetransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingsignup',
            name='mobile_number',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='referraluser',
            name='referral_code',
            field=models.CharField(default=website.models.generate_referral_code, max_length=10),
        ),
    ]
