# Generated by Django 5.2.11 on 2026-03-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_adminuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagecontent',
            name='trust_item1',
            field=models.CharField(default='Made for Indian Retailers', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='trust_item2',
            field=models.CharField(default='GST-Ready', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='trust_item3',
            field=models.CharField(default='Secure Cloud Data', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='trust_item4',
            field=models.CharField(default='24/7 Support', max_length=200),
        ),
    ]
