# Generated by Django 5.2.11 on 2026-03-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_landingpagecontent_trust_item1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagecontent',
            name='problem1_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='problem1_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='problem2_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='problem2_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='problem3_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='problem3_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='problem4_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='problem4_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='problem5_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='problem5_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='problem_section_label',
            field=models.CharField(blank=True, default='THE CHALLENGE', max_length=100),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='problem_section_title',
            field=models.CharField(blank=True, default='Retailers Face These Daily Problems', max_length=255),
        ),
    ]
