# Generated by Django 5.2.11 on 2026-03-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_landingpagecontent_problem1_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagecontent',
            name='solution1_desc',
            field=models.TextField(blank=True, default='Lightning-fast billing with GST compliance'),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='solution1_title',
            field=models.CharField(blank=True, default='POS Billing', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='solution2_desc',
            field=models.TextField(blank=True, default='Real-time stock tracking & alerts'),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='solution2_title',
            field=models.CharField(blank=True, default='Inventory Management', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='solution3_desc',
            field=models.TextField(blank=True, default='Customer management & loyalty programs'),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='solution3_title',
            field=models.CharField(blank=True, default='CRM & Loyalty', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='solution4_desc',
            field=models.TextField(blank=True, default='Automated bookkeeping & reports'),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='solution4_title',
            field=models.CharField(blank=True, default='Accounting', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='solution5_desc',
            field=models.TextField(blank=True, default='Attendance, payroll & performance'),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='solution5_title',
            field=models.CharField(blank=True, default='Employee Management', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='solution6_desc',
            field=models.TextField(blank=True, default='Insights at a glance with smart analytics'),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='solution6_title',
            field=models.CharField(blank=True, default='Reports & Dashboard', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='solution_section_label',
            field=models.CharField(blank=True, default='THE SOLUTION', max_length=100),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='solution_section_title',
            field=models.CharField(blank=True, default='One Smart ERP For Complete Store Management', max_length=255),
        ),
    ]
