# Generated by Django 5.2.11 on 2026-03-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_landingpagecontent_solution1_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagecontent',
            name='nobarcode_desc',
            field=models.TextField(blank=True, default='Our AI technology identifies products from photos - Just snap and bill. No barcode scanner needed. Lightning-fast, accurate, and incredibly simple.'),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='nobarcode_features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='nobarcode_label',
            field=models.CharField(blank=True, default='AI Powered(BETA FEATURE)', max_length=100),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='nobarcode_title',
            field=models.CharField(blank=True, default='No Barcode? No Problem.', max_length=255),
        ),
    ]
