# Generated by Django 5.2.11 on 2026-03-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_landingpagecontent_nobarcode_desc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='nobarcode_desc',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='nobarcode_features',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='nobarcode_label',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='nobarcode_title',
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='usp_badge_text',
            field=models.CharField(blank=True, default='AI-Powered (Beta Feature)', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='usp_description',
            field=models.TextField(blank=True, default='Our AI technology identifies products from photos — just snap and bill. No barcode scanner needed. Lightning-fast, accurate, and incredibly simple.'),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='usp_feature1_desc',
            field=models.TextField(default='Instant product recognition from images'),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='usp_feature1_title',
            field=models.CharField(default='Photo-Based Product Detection', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='usp_feature2_desc',
            field=models.TextField(default='Smart AI-powered identification system'),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='usp_feature2_title',
            field=models.CharField(default='AI Auto Identify Product', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='usp_feature3_desc',
            field=models.TextField(default='Seamless one-click billing integration'),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='usp_feature3_title',
            field=models.CharField(default='Add Directly to Bill', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='usp_title',
            field=models.CharField(blank=True, default='No Barcode? No Problem.', max_length=200),
        ),
    ]
