# Generated by Django 5.2.11 on 2026-03-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_remove_landingpagecontent_nobarcode_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagecontent',
            name='howitworks_label',
            field=models.CharField(blank=True, default='Simple Process', max_length=100),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='howitworks_step1_desc',
            field=models.CharField(blank=True, default='Schedule a quick demo with our team', max_length=255),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='howitworks_step1_title',
            field=models.CharField(blank=True, default='Book Demo', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='howitworks_step2_desc',
            field=models.CharField(blank=True, default='We configure everything for you', max_length=255),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='howitworks_step2_title',
            field=models.CharField(blank=True, default='Setup & Training', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='howitworks_step3_desc',
            field=models.CharField(blank=True, default='Go live and start selling instantly', max_length=255),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='howitworks_step3_title',
            field=models.CharField(blank=True, default='Start Smart Billing', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='howitworks_title',
            field=models.CharField(blank=True, default='How It Works', max_length=255),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='pricing_button',
            field=models.CharField(blank=True, default='Get Started Today', max_length=100),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='pricing_duration',
            field=models.CharField(blank=True, default='per year + GST', max_length=100),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='pricing_feature1',
            field=models.CharField(blank=True, default='POS Billing + Inventory', max_length=255),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='pricing_feature2',
            field=models.CharField(blank=True, default='CRM & Loyalty Program', max_length=255),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='pricing_feature3',
            field=models.CharField(blank=True, default='Accounting Reports', max_length=255),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='pricing_feature4',
            field=models.CharField(blank=True, default='AI Product Detection', max_length=255),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='pricing_feature5',
            field=models.CharField(blank=True, default='24/7 Support', max_length=255),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='pricing_label',
            field=models.CharField(blank=True, default='Pricing', max_length=100),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='pricing_plan_name',
            field=models.CharField(blank=True, default='AI Retailer Package', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='pricing_price',
            field=models.CharField(blank=True, default='₹12,000', max_length=50),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='pricing_title',
            field=models.CharField(blank=True, default='Simple & Transparent Pricing', max_length=255),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='who1',
            field=models.CharField(blank=True, default='Kirana Stores', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='who2',
            field=models.CharField(blank=True, default='General Stores', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='who3',
            field=models.CharField(blank=True, default='Medical Shops', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='who4',
            field=models.CharField(blank=True, default='Hardware Stores', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='who5',
            field=models.CharField(blank=True, default='Margin Business Retailers', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='who_main_title',
            field=models.CharField(blank=True, default='Perfect For', max_length=255),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='who_title',
            field=models.CharField(blank=True, default='Who Is This For?', max_length=255),
        ),
    ]
