# Generated by Django 5.2.11 on 2026-03-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_landingpagecontent_howitworks_label_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='pricing_button',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='pricing_duration',
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='pricing_feature6',
            field=models.CharField(blank=True, default='Setup & Training Support', max_length=255),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='pricing_feature7',
            field=models.CharField(blank=True, default='24/7 Customer Support', max_length=255),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='pricing_feature8',
            field=models.CharField(blank=True, default='AI Photo Billing', max_length=255),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='pricing_old_price',
            field=models.CharField(blank=True, default='₹29,999', max_length=50),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='pricing_price_suffix',
            field=models.CharField(blank=True, default='+ GST', max_length=50),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='pricing_feature1',
            field=models.CharField(blank=True, default='Full Access to All Modules', max_length=255),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='pricing_feature2',
            field=models.CharField(blank=True, default='POS Billing + Inventory', max_length=255),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='pricing_feature3',
            field=models.CharField(blank=True, default='CRM & Loyalty Programs', max_length=255),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='pricing_feature4',
            field=models.CharField(blank=True, default='Accounting & Reports', max_length=255),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='pricing_feature5',
            field=models.CharField(blank=True, default='Employee Management', max_length=255),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='pricing_label',
            field=models.CharField(blank=True, default='PRICING', max_length=100),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='pricing_plan_name',
            field=models.CharField(blank=True, default='All-Inclusive Package', max_length=200),
        ),
    ]
