# Generated by Django 5.2.11 on 2026-03-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_remove_landingpagecontent_pricing_button_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagecontent',
            name='join_referral',
            field=models.CharField(default='Join Referral Program', max_length=50),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='referral_item1_text',
            field=models.CharField(blank=True, default='Per Successful Sale', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='referral_item1_value',
            field=models.CharField(blank=True, default='₹2,000', max_length=100),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='referral_item2_text',
            field=models.CharField(blank=True, default='Renewal Incentive', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='referral_item2_value',
            field=models.CharField(blank=True, default='₹1,000', max_length=100),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='referral_item3_text',
            field=models.CharField(blank=True, default='For Every Successful Referral Purchase', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='referral_item3_value',
            field=models.CharField(blank=True, default='₹1,000', max_length=100),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='referral_item4_text',
            field=models.CharField(blank=True, default='Referral Income', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='referral_item4_value',
            field=models.CharField(blank=True, default='Unlimited', max_length=100),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='referral_label',
            field=models.CharField(blank=True, default='REFERRAL PROGRAM', max_length=100),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='referral_title',
            field=models.CharField(blank=True, default='Earn With AI-Setu ERP', max_length=255),
        ),
    ]
