# Generated by Django 5.2.11 on 2026-03-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_landingpagecontent_join_referral_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagecontent',
            name='comparison_feature1',
            field=models.CharField(default='AI Photo Billing', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='comparison_feature2',
            field=models.CharField(default='Simple Interface', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='comparison_feature3',
            field=models.CharField(default='One Package Pricing', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='comparison_feature4',
            field=models.CharField(default='Retail-Focused', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='comparison_feature5',
            field=models.CharField(default='GST Ready', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='comparison_feature6',
            field=models.CharField(default='Cloud Access', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='comparison_feature7',
            field=models.CharField(default='24/7 Support', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='comparison_subtitle',
            field=models.CharField(blank=True, default='Discover why retailers are switching to AI-Setu ERP for faster, smarter store management.', max_length=255),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='comparison_title',
            field=models.CharField(blank=True, default='AI-Setu ERP vs Traditional Software', max_length=255),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='comparison_title1',
            field=models.CharField(default='Feature', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='comparison_title2',
            field=models.CharField(default='AI-Setu ERP', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='comparison_title3',
            field=models.CharField(default='Traditional', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='faq1_answer',
            field=models.TextField(blank=True, default='Yes! AI-Setu ERP is fully GST compliant with automatic tax calculations, GSTIN integration, and GST-ready invoicing.'),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='faq1_question',
            field=models.CharField(blank=True, default='Is it GST Ready?', max_length=255),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='faq2_answer',
            field=models.TextField(blank=True, default='AI-Setu ERP is cloud-based for the best experience. However, basic billing can work offline and syncs when internet is available.'),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='faq2_question',
            field=models.CharField(blank=True, default='Is Internet Required?', max_length=255),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='faq3_answer',
            field=models.TextField(blank=True, default='No! Our AI-powered photo detection lets you bill products without barcodes — just snap a photo and the product is identified automatically.'),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='faq3_question',
            field=models.CharField(blank=True, default='Do I need Barcode?', max_length=255),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='faq4_answer',
            field=models.TextField(blank=True, default='Yes, we provide 24/7 customer support via phone, email, and chat. Our team is always ready to help.'),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='faq4_question',
            field=models.CharField(blank=True, default='Is Support Provided?', max_length=255),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='faq5_answer',
            field=models.TextField(blank=True, default='Annual renewal is available at a competitive rate. Refer others and earn ₹1,000 per renewal incentive!'),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='faq5_question',
            field=models.CharField(blank=True, default='What About Renewal?', max_length=255),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='faq_title',
            field=models.CharField(blank=True, default='Frequently Asked Questions', max_length=255),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='testimonial1_name',
            field=models.CharField(blank=True, default='Rajesh Patel', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='testimonial1_role',
            field=models.CharField(blank=True, default='Kirana Store,Surat', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='testimonial1_text',
            field=models.TextField(blank=True, default='AI-Setu ERP transformed my billing process. The AI photo detection is a game changer — no more barcode hassles!'),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='testimonial2_name',
            field=models.CharField(blank=True, default='Priya Sharma', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='testimonial2_role',
            field=models.CharField(blank=True, default='Medical Shop,Surat', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='testimonial2_text',
            field=models.TextField(blank=True, default='Simple to use and my staff learned it in one day. GST billing is now automatic. Highly recommended!'),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='testimonial3_name',
            field=models.CharField(blank=True, default='Amit Desai', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='testimonial3_role',
            field=models.CharField(blank=True, default='General Store, Vadodara', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='testimonial3_text',
            field=models.TextField(blank=True, default='Finally an ERP that understands Indian retail. The pricing is fair and support team is always available.'),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='testimonial_label',
            field=models.CharField(blank=True, default='TESTIMONIALS', max_length=100),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='testimonial_title',
            field=models.CharField(blank=True, default='What Our Customers Say', max_length=255),
        ),
    ]
