# Generated by Django 5.2.11 on 2026-03-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_landingpagecontent_comparison_feature1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagecontent',
            name='faq6_answer',
            field=models.TextField(blank=True, default='Annual renewal is available at a competitive rate. Refer others and earn ₹1,000 per renewal incentive!'),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='faq6_question',
            field=models.CharField(blank=True, default='What About Renewal?', max_length=255),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='faq5_answer',
            field=models.TextField(blank=True, default='Absolutely. We provide complete setup and training for you and your staff as part of the package.'),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='faq5_question',
            field=models.CharField(blank=True, default='Is Training Included?', max_length=255),
        ),
    ]
