# Generated by Django 5.2.11 on 2026-03-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_landingpagecontent_faq6_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagecontent',
            name='cta_badge',
            field=models.CharField(blank=True, default='Join 500+ Happy Retailers', max_length=200),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='cta_button_text',
            field=models.CharField(blank=True, default='Book Free Demo', max_length=100),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='cta_description',
            field=models.TextField(blank=True, default="Join hundreds of Indian retailers who've switched to smarter billing with AI-Setu ERP. Get started in minutes, no tech skills needed."),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='cta_small_text',
            field=models.CharField(blank=True, default='No credit card required · Free setup · Cancel anytime', max_length=255),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='cta_title',
            field=models.CharField(blank=True, default='Ready to Upgrade Your Store?', max_length=255),
        ),
    ]
