# Generated by Django 5.2.11 on 2026-03-13 08:19

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0038_policycontent_policysection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='lucide-react icon name (clock, package, trending-down, users, barcode)', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='policysection',
            name='policy',
        ),
        migrations.DeleteModel(
            name='PolicyContent',
        ),
        migrations.DeleteModel(
            name='PolicySection',
        ),
    ]
