# Generated by Django 5.2.11 on 2026-03-13 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0039_problem_remove_policysection_policy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='problem1_description',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='problem1_title',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='problem2_description',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='problem2_title',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='problem3_description',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='problem3_title',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='problem4_description',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='problem4_title',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='problem5_description',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='problem5_title',
        ),
    ]
