# Generated by Django 5.2.11 on 2026-03-13 09:11

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0041_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='USPFeature',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='solution1_desc',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='solution1_title',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='solution2_desc',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='solution2_title',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='solution3_desc',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='solution3_title',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='solution4_desc',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='solution4_title',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='solution5_desc',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='solution5_title',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='solution6_desc',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='solution6_title',
        ),
    ]
