# Generated by Django 5.2.11 on 2026-03-13 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0042_uspfeature_remove_landingpagecontent_solution1_desc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='usp_feature1_desc',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='usp_feature1_title',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='usp_feature2_desc',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='usp_feature2_title',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='usp_feature3_desc',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='usp_feature3_title',
        ),
    ]
