# Generated by Django 5.2.11 on 2026-03-13 09:23

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0043_remove_landingpagecontent_usp_feature1_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowItWorksStep',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=50)),
                ('step_number', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
    ]
