# Generated by Django 5.2.11 on 2026-03-13 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0044_howitworksstep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='howitworks_step1_desc',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='howitworks_step1_title',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='howitworks_step2_desc',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='howitworks_step2_title',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='howitworks_step3_desc',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='howitworks_step3_title',
        ),
    ]
