# Generated by Django 5.2.11 on 2026-03-13 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0046_storetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='who1',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='who2',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='who3',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='who4',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='who5',
        ),
    ]
