# Generated by Django 5.2.11 on 2026-03-13 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0048_referralperk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='referral_item1_text',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='referral_item1_value',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='referral_item2_text',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='referral_item2_value',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='referral_item3_text',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='referral_item3_value',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='referral_item4_text',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='referral_item4_value',
        ),
    ]
