# Generated by Django 5.2.11 on 2026-03-13 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0050_testimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='testimonial1_name',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='testimonial1_role',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='testimonial1_text',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='testimonial2_name',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='testimonial2_role',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='testimonial2_text',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='testimonial3_name',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='testimonial3_role',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='testimonial3_text',
        ),
    ]
