# Generated by Django 5.2.11 on 2026-03-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0051_remove_landingpagecontent_testimonial1_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagecontent',
            name='review_button',
            field=models.CharField(default='View All Reviews', max_length=50),
        ),
    ]
