# Generated by Django 5.2.11 on 2026-03-14 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0052_landingpagecontent_review_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagecontent',
            name='all_reviews_desc',
            field=models.CharField(default='See what retailers across India are saying about AI-Setu ERP.', max_length=255),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='all_reviews_title',
            field=models.CharField(default='Customer Reviews', max_length=255),
        ),
    ]
