# Generated by Django 5.2.11 on 2026-03-14 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0059_demovideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='faq1_answer',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='faq1_question',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='faq2_answer',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='faq2_question',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='faq3_answer',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='faq3_question',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='faq4_answer',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='faq4_question',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='faq5_answer',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='faq5_question',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='faq6_answer',
        ),
        migrations.RemoveField(
            model_name='landingpagecontent',
            name='faq6_question',
        ),
    ]
