# Generated by Django 5.2.11 on 2026-03-14 09:18

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0061_blogcategory_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllStoreType',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Store Type',
                'verbose_name_plural': 'All Store Types',
            },
        ),
    ]
