# Generated by Django 5.2.11 on 2026-03-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0062_allstoretype'),
    ]

    operations = [
        migrations.AddField(
            model_name='allstoretype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
