# Generated by Django 5.2.11 on 2026-03-16 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0062_contactpagecontent_call_phone_number_and_more'),
        ('website', '0063_allstoretype_is_active'),
    ]

    operations = [
    ]
