# Generated by Django 5.2.11 on 2026-03-16 07:12

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0064_merge_20260316_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='Smart ERP for Indian retailers. AI-powered billing & store management.')),
                ('email', models.EmailField(default='ceo@hkdigiverse.com', max_length=254)),
                ('address', models.TextField(default='501-502, Silver Trade Center, Mota Varachha, Surat, Gujarat, India - 394101')),
                ('phone', models.CharField(default='+91 12345 67890', max_length=20)),
                ('quick_links', models.JSONField(default=list)),
                ('policies', models.JSONField(default=list)),
            ],
        ),
    ]
