# Generated by Django 5.2.11 on 2026-03-16 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0065_footer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CareerPageContent',
        ),
    ]
