# Generated by Django 5.2.11 on 2026-03-16 08:49

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0066_delete_careerpagecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPage',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(max_length=255)),
                ('hero_subtitle', models.TextField()),
                ('culture_title', models.CharField(default='Our Culture', max_length=200)),
                ('perks_title', models.CharField(default='Perks & Benefits', max_length=200)),
                ('cta_title', models.CharField(max_length=255)),
                ('cta_subtitle', models.TextField()),
                ('cta_button_text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('career_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultures', to='website.careerpage')),
            ],
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('career_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='website.careerpage')),
            ],
        ),
        migrations.CreateModel(
            name='Perk',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('career_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perks', to='website.careerpage')),
            ],
        ),
    ]
