# Generated by Django 5.2.11 on 2026-03-16 10:01

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0067_careerpage_culture_jobposition_perk'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildJobPosition',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('location', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('career_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='website.careerpage')),
            ],
        ),
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='website.childjobposition')),
            ],
        ),
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='website.childjobposition')),
            ],
        ),
    ]
