# Generated by Django 5.2.11 on 2026-03-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0068_childjobposition_jobdescription_jobskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='childjobposition',
            name='cta_apply',
            field=models.CharField(default='Apply For this Job', max_length=100),
        ),
    ]
