# Generated by Django 5.2.11 on 2026-03-16 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0069_childjobposition_cta_apply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childjobposition',
            name='cta_apply',
        ),
    ]
