# Generated by Django 5.2.11 on 2026-03-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0072_delete_aboutpagecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposition',
            name='total_positions',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='work_place',
            field=models.CharField(default='WFO', max_length=100),
        ),
    ]
