# Generated by Django 5.2.11 on 2026-03-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0073_jobposition_total_positions_jobposition_work_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposition',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
