# Generated by Django 5.2.11 on 2026-03-17 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0074_jobposition_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobposition',
            old_name='slug',
            new_name='job_slug',
        ),
    ]
