# Generated by Django 6.0.3 on 2026-03-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0081_payment_response_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='seo_description',
            field=models.TextField(blank=True, help_text='Meta description for SEO (max 160 chars recommended)', null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated SEO keywords', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Meta title for SEO (max 70 chars recommended)', max_length=255, null=True),
        ),
    ]
