# Generated by Django 6.0.3 on 2026-03-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0082_blogpost_seo_description_blogpost_seo_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerpage',
            name='seo_description',
            field=models.TextField(blank=True, help_text='Meta description for SEO (max 160 chars recommended)', null=True),
        ),
        migrations.AddField(
            model_name='careerpage',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated SEO keywords', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='careerpage',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Meta title for SEO (max 70 chars recommended)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='childjobposition',
            name='seo_description',
            field=models.TextField(blank=True, help_text='Meta description for SEO (max 160 chars recommended)', null=True),
        ),
        migrations.AddField(
            model_name='childjobposition',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated SEO keywords', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='childjobposition',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Meta title for SEO (max 70 chars recommended)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='seo_description',
            field=models.TextField(blank=True, help_text='Meta description for SEO (max 160 chars recommended)', null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated SEO keywords', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactpagecontent',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Meta title for SEO (max 70 chars recommended)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='seo_description',
            field=models.TextField(blank=True, help_text='Meta description for SEO (max 160 chars recommended)', null=True),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated SEO keywords', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Meta title for SEO (max 70 chars recommended)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='seo_description',
            field=models.TextField(blank=True, help_text='Meta description for SEO (max 160 chars recommended)', null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated SEO keywords', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landingpagecontent',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Meta title for SEO (max 70 chars recommended)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='seo_description',
            field=models.TextField(blank=True, help_text='Meta description for SEO (max 160 chars recommended)', null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated SEO keywords', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Meta title for SEO (max 70 chars recommended)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='seo_description',
            field=models.TextField(blank=True, help_text='Meta description for SEO (max 160 chars recommended)', null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated SEO keywords', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Meta title for SEO (max 70 chars recommended)', max_length=255, null=True),
        ),
    ]
