# Generated by Django 5.2.11 on 2026-03-19 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0083_careerpage_seo_description_careerpage_seo_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingsignup',
            name='mobile_number',
            field=models.CharField(max_length=15),
        ),
    ]
