# Generated by Django 5.2.11 on 2026-03-21 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0087_aboutusserveitem_about_page_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralProgramContent',
            fields=[
            ],
            options={
                'verbose_name': 'Referral Program Content',
                'verbose_name_plural': 'Referral Program Content',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.landingpagecontent',),
        ),
        migrations.AddField(
            model_name='referralperk',
            name='landing_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_perks', to='website.landingpagecontent'),
        ),
    ]
