# Generated by Django 6.0.3 on 2026-03-21 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0088_referralprogramcontent_referralperk_landing_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonfeature',
            name='landing_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comparison_features', to='website.landingpagecontent'),
        ),
        migrations.AddField(
            model_name='faq',
            name='landing_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='website.landingpagecontent'),
        ),
        migrations.AddField(
            model_name='feature',
            name='landing_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='website.landingpagecontent'),
        ),
        migrations.AddField(
            model_name='howitworksstep',
            name='landing_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='howitworks_steps', to='website.landingpagecontent'),
        ),
        migrations.AddField(
            model_name='problem',
            name='landing_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='website.landingpagecontent'),
        ),
        migrations.AddField(
            model_name='storetype',
            name='landing_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_types', to='website.landingpagecontent'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='landing_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='website.landingpagecontent'),
        ),
        migrations.AddField(
            model_name='uspfeature',
            name='landing_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usp_features', to='website.landingpagecontent'),
        ),
    ]
