# Generated by Django 5.2.11 on 2026-03-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0102_sociallink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='icon',
            field=models.CharField(help_text='Lucide icon name (e.g. Zap, BarChart3, Shield). See lucide.dev for all options.', max_length=50),
        ),
        migrations.AlterField(
            model_name='howitworksstep',
            name='icon',
            field=models.CharField(help_text='Lucide icon name (e.g. Search, Pencil, Check). See lucide.dev', max_length=50),
        ),
        migrations.AlterField(
            model_name='problem',
            name='icon',
            field=models.CharField(help_text='Lucide icon name (e.g. Clock, Package, TrendingDown, Users, Barcode). See lucide.dev for all options.', max_length=50),
        ),
        migrations.AlterField(
            model_name='referralperk',
            name='icon',
            field=models.CharField(help_text='Lucide icon name (e.g. Gift, Tag, Ticket). See lucide.dev', max_length=50),
        ),
        migrations.AlterField(
            model_name='storetype',
            name='icon',
            field=models.CharField(help_text='Lucide icon name (e.g. Store, ShoppingBag, Truck). See lucide.dev', max_length=50),
        ),
        migrations.AlterField(
            model_name='uspfeature',
            name='icon',
            field=models.CharField(help_text='Lucide icon name (e.g. Star, Zap, Activity). See lucide.dev', max_length=50),
        ),
    ]
