# Generated by Django 5.2.11 on 2026-04-02 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0103_alter_feature_icon_alter_howitworksstep_icon_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policy',
            options={'verbose_name_plural': 'Policies'},
        ),
        migrations.AddField(
            model_name='pricingsignup',
            name='state',
            field=models.CharField(default='Gujarat', max_length=100),
        ),
        migrations.AlterField(
            model_name='culture',
            name='icon',
            field=models.CharField(blank=True, help_text='Lucide icon name (e.g. Heart, Target, Users). See lucide.dev', max_length=100),
        ),
    ]
