# Generated by Django 5.2.12 on 2026-04-03 12:08

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0104_alter_policy_options_pricingsignup_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host_user', models.EmailField(default='hkdigiverse@gmail.com', help_text='The email address to use for sending emails (e.g. your Gmail ID)', max_length=255)),
                ('email_host_password', models.CharField(default='your-app-password', help_text='The App Password for the email account (NOT your regular password)', max_length=255)),
                ('active_payment_gateway', models.CharField(choices=[('PHONEPE', 'PhonePe'), ('RAZORPAY', 'Razorpay')], default='PHONEPE', help_text='Switch between payment gateways (PhonePe or Razorpay)', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('PHONEPE', 'PhonePe'), ('RAZORPAY', 'Razorpay')], default='PHONEPE', max_length=20),
        ),
    ]
