# Generated by Django 5.2.12 on 2026-04-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0105_globalsettings_payment_gateway'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalsettings',
            name='active_payment_gateway',
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('RAZORPAY', 'Razorpay')], default='RAZORPAY', max_length=20),
        ),
    ]
