# Generated by Django 5.2.12 on 2026-04-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0106_remove_globalsettings_active_payment_gateway_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingsignup',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
