# Generated by Django 5.2.12 on 2026-04-03 12:12

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0105_globalsettings_payment_gateway'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmissionProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.contactsubmission',),
        ),
        migrations.CreateModel(
            name='DemoRequestProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Demo Request',
                'verbose_name_plural': 'Demo Requests',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.demorequest',),
        ),
        migrations.CreateModel(
            name='JobApplicationProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.jobapplication',),
        ),
        migrations.CreateModel(
            name='PaymentProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.payment',),
        ),
        migrations.CreateModel(
            name='PricingSignupProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Pricing Signup',
                'verbose_name_plural': 'Pricing Signups',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.pricingsignup',),
        ),
    ]
